### ISSUE TITLE
Unable to install on Arm architechture

### ISSUE THREAD

**Issue by JoshLoecker** [hklarner/pyboolnet#113]
I have an Apple SIlicon MacBook and I am getting the following errors on install

```
> pip install git+https://github.com/hklarner/pyboolnet
Collecting git+https://github.com/hklarner/pyboolnet
  Cloning https://github.com/hklarner/pyboolnet to /private/var/folders/6s/9l9z74v90tn8lprrp7fchb9w0000gn/T/pip-req-build-x_3iazut
  Running command git clone --filter=blob:none --quiet https://github.com/hklarner/pyboolnet /private/var/folders/6s/9l9z74v90tn8lprrp7fchb9w0000gn/T/pip-req-build-x_3iazut
  Resolved https://github.com/hklarner/pyboolnet to commit 5ae3bc75127d8c06a4c077819f2be06be8af22aa
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      detected os and binaries: THIS_OS='Darwin', BINARIES_SOURCE_DIR='binaries/max64'
      Traceback (most recent call last):
        File "/Users/joshl/Projects/MechanisticLLM/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/joshl/Projects/MechanisticLLM/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/joshl/Projects/MechanisticLLM/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/6s/9l9z74v90tn8lprrp7fchb9w0000gn/T/pip-build-env-5kq9huax/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/6s/9l9z74v90tn8lprrp7fchb9w0000gn/T/pip-build-env-5kq9huax/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/6s/9l9z74v90tn8lprrp7fchb9w0000gn/T/pip-build-env-5kq9huax/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/6s/9l9z74v90tn8lprrp7fchb9w0000gn/T/pip-build-env-5kq9huax/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 34, in <module>
        File "/private/var/folders/6s/9l9z74v90tn8lprrp7fchb9w0000gn/T/pip-build-env-5kq9huax/overlay/lib/python3.11/site-packages/setuptools/_distutils/dir_util.py", line 136, in copy_tree
          raise DistutilsFileError("cannot copy tree '%s': not a directory" % src)
      distutils.errors.DistutilsFileError: cannot copy tree 'binaries/max64': not a directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by hklarner** [comment]
Hi Josh. I found the problem, it is fixed in version `3.0.13`, can you confirm?

```
pip3 install git+https://github.com/hklarner/pyboolnet@3.0.13
```

**Comment by JoshLoecker** [comment]
Yes, I can install now. Thank you for the speedy fix! :)
