### ISSUE TITLE
install from tar.gz does not work anymore

### ISSUE THREAD

**Issue by hklarner** [hklarner/PyBoolNet#40]
@carissableker @aurelien-naldi 

I have noticed that building `PyBoolNet-2.2.9_linux64.tar.gz` and installing with `pip3` now fails with message

```
distutils.errors.DistutilsFileError: cannot copy tree 'Dependencies/linux64': not a directory
```

Can you reproduce this? Here are the steps:

```
~$ git clone git@github.com:hklarner/PyBoolNet.git
...
~$ cd PyBoolNet
~$ ./make_release.sh
...
~$ pip3 install dist/PyBoolNet-2.2.9_linux64.tar.gz
Defaulting to user installation because normal site-packages is not writeable
Processing ./dist/PyBoolNet-2.2.9_linux64.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-206pfb9u/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-206pfb9u/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-u8dlw7jt
         cwd: /tmp/pip-req-build-206pfb9u/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-206pfb9u/setup.py", line 23, in <module>
        copy_tree(pyboolnet_dep_folder, os.path.join("PyBoolNet", "Dependencies"))
      File "/usr/lib/python3.6/distutils/dir_util.py", line 127, in copy_tree
        "cannot copy tree '%s': not a directory" % src)
    distutils.errors.DistutilsFileError: cannot copy tree 'Dependencies/linux64': not a directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
But the directory exists:

```
~$ cd Dependencies/linux64
~$ ls
BNetToPrime  clasp-3.1.1  eqntott  espresso  gringo-4.4.0  NuSMV-a  nusmvkeywords.json  settings.cfg
```

**Comment by carissableker** [comment]
I reproduced it. I think it's a path/absolute path issue. It is possible to install after cloning without running `make_release.sh` though:

```
$ git clone git@github.com:hklarner/PyBoolNet.git
$ cd PyBoolNet
$ pip install .
Processing /Processing /home/-/test/PyBoolNet
Collecting networkx==2.4
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting decorator>=4.3.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Building wheels for collected packages: PyBoolNet
  Building wheel for PyBoolNet (setup.py) ... done
  Created wheel for PyBoolNet: filename=PyBoolNet-2.2.9-py3-none-any.whl size=7075660 sha256=130087854df06f7a6b83212a487a4c8e9712a29b398f414526dd535c6a9afe11
  Stored in directory: /tmp/pip-ephem-wheel-cache-udtnnfeu/wheels/53/5b/b3/c0b8543293f982ee8e3491fa1d0dc4ba7c5dc6b7795f13a37c
Successfully built PyBoolNet
Installing collected packages: decorator, networkx, PyBoolNet
Successfully installed PyBoolNet-2.2.9 decorator-4.4.2 networkx-2.4
/cbleker/test/PyBoolNet
Collecting networkx==2.4
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting decorator>=4.3.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Building wheels for collected packages: PyBoolNet
  Building wheel for PyBoolNet (setup.py) ... done
  Created wheel for PyBoolNet: filename=PyBoolNet-2.2.9-py3-none-any.whl size=7075660 sha256=130087854df06f7a6b83212a487a4c8e9712a29b398f414526dd535c6a9afe11
  Stored in directory: /tmp/pip-ephem-wheel-cache-udtnnfeu/wheels/53/5b/b3/c0b8543293f982ee8e3491fa1d0dc4ba7c5dc6b7795f13a37c
Successfully built PyBoolNet
Installing collected packages: decorator, networkx, PyBoolNet
Successfully installed PyBoolNet-2.2.9 decorator-4.4.2 networkx-2.4
```
I can look into the path issue.

**Comment by carissableker** [comment]
Oh... duh. 
 
`setup.py` now looks for the dependencies in PyBoolNet/Dependencies/<os> and moves them to PyBoolNet/PyBoolNet/Dependencies/

But `make_relase.sh` has already moved the (os dependent) dependencies to PyBoolNet/PyBoolNet/Dependencies/

**Comment by hklarner** [comment]
Can confirm that
```
$ pip3 install .
```
works.

> But make_relase.sh has already moved

I am not clear on what's happening here. Do you see an easy fix? Otherwise, now that `pip3 install .` works I am not sure I need `pip3 install dist/PyBoolNet-2.2.9_linux64.tar.gz` to work anymore.

**Comment by carissableker** [comment]
Oh... duh. 
 
`setup.py` now looks for the dependencies in PyBoolNet/Dependencies/<os>/ and moves them to PyBoolNet/PyBoolNet/Dependencies/

But `make_relase.sh` has already moved the (os dependent) dependencies to PyBoolNet/PyBoolNet/Dependencies/, and PyBoolNet/Dependencies/ has disappeared so `setup.py` freaks out.

**Comment by carissableker** [comment]
Not sure how to fix it, as I mentioned [here](https://github.com/hklarner/PyBoolNet/issues/16#issuecomment-652888149). 

It is probably possible to fix it, I would need to look into what `python3 setup.py sdist` is doing.

**Comment by hklarner** [comment]
Ok. Let's just leave it open as a known bug. I don't think it affects any users and `pip3 install .` should be a valid alternative.
